language: python
python:
  - "3.7"

cache:
  pip: true

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

script:
  - coverage run --include=rest_framework_extras/tests/* manage.py test

after_success:
  - coveralls