language: python

env:
  - TOXENV=django19-py27
  - TOXENV=django19-py35
  - TOXENV=coverage


matrix:
    include:
        - python: 2.7
          env: TOXENV=django19-27
        - python: 3.5
          env: TOXENV=django19-py35
        - python: pypy
          env: TOXENV=django19-pypy27

install:
  - pip install tox
  - pip install coverage
  - pip install coveralls

script: tox
