language: python

matrix:
    include:
        - python: 2.7
          env: TOXENV=django111-py27
        - python: 3.5
          env: TOXENV=django111-py35
        - python: pypy
          env: TOXENV=django111-pypy27
        - python: 3.5
          env: TOXENV=django20
        - python: 2.7
          env: TOXENV=coverage

install:
  - pip install tox
  - pip install coverage
  - pip install coveralls

script: tox
