language: python

matrix:
    include:
        - python: 3.6
          env: TOXENV=django111-py36
        - python: 3.6
          env: TOXENV=django20-py36
        - python: 3.6
          env: TOXENV=coverage

install:
  - pip install --upgrade pip
  - pip install tox
  - pip install coverage
  - pip install coveralls

script: tox
